import { Injectable } from '@angular/core';
import { Books } from './shared/book';
import { Tag } from './shared/models/Tag';
@Injectable({
  providedIn: 'root'
})
export class StoreService {

  constructor() { }

 getBookById(id:number){
  return this.getAll().find(book => book.id === String(id))!;
 }

  getAllBookByTag(tag:string) :Books[]{
    return tag == "All"?
    this.getAll() : this.getAll().filter(book =>book.tags?.includes(tag));
    //you can write this statement is very simpletype lets do it.
  }

  getAllTag():Tag[]{
    return[
      {name:'All',count: 50},
      {name:'Premium PGs',count:11},
      {name:'Unisex PGs',count:10},
      {name:'Girls PGs',count:18},
      {name:'Boys PGs',count:11},
    ];

  }
  getAll():Books[]{
    return[
      {
      name:'SMS Boys PG',
      id:'101',
      Owner:['B.Sunil Ram' , '8978799789'],
      Address:'2JP9+PJ6, Govindapura, Nagavara, , Bengaluru, Karnataka 560045',
      price:5999,
      availability:'Available',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :4.0,
      imageUrl:'/assets/front page/bpg2.jpg',
      aboutTheBook:'"Atomic Habits" by James Clear is a bestselling self-help book that focuses on the power of small habits and their impact on our lives. It provides a framework for understanding habit formation and offers practical strategies to create positive habits and break negative ones. Clear explores the habit loop, discusses the importance of cues and rewards, and suggests techniques to make habits obvious, attractive, easy, and satisfying. The book also addresses challenges like procrastination and offers advice on staying motivated and overcoming setbacks. "Atomic Habits" is known for its practicality and evidence-based approach, and it has become a popular resource for personal growth and behavior change',
      aboutTheOwner:'James Clear is an expert on habits and decision making. He made his name as the Owner of one of the fastest-growing email newsletters in history, which grew from zero to 100,000 subscribers in under two years. Today, his newsletter has over 400,000 subscribers and his articles at jamesclear receive 10 million hits each year. His work frequently appears in publications including the New York Times, Forbes and Business Insider',
      reviews:'No review found',
      tags:['Boys PGs','Two Sharing'],
      },
      {
        name:'AMB Girls PG ',
        id:'102',
        Owner:['K.HariKrishna', '9786889788'],
        Address:'RGA Techpark backside, 54/1, Mainroad, Carmelaram, Hadosiddapura , Chikkakannalli, Bengaluru, Karnataka 560035',
        price:5999,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/front page/bpg1.avif',
        aboutTheBook:'Timeless lessons on wealth, greed, and happiness doing well with money isn’t necessarily about what you know. It’s about how you behave. And behavior is hard to teach, even to really smart people. How to manage money, invest it, and make business decisions are typically considered to involve a lot of mathematical calculations, where data and formulae tell us exactly what to do. But in the real world, people don’t make financial decisions on a spreadsheet. They make them at the dinner table, or in a meeting room, where personal history, your unique view of the world, ego, pride, marketing, and odd incentives are scrambled together. In the psychology of money, the Owner shares 19 short stories exploring the strange ways people think about money and teaches you how to make better sense of one of life’s most important matters.',
        aboutTheOwner:'Morgan Housel is a partner at The Collaborative Fund and a former columnist at The Motley Fool and The Wall Street Journal. He is a two-time winner of the Best in Business Award from the Society of American Business Editors and Writers, winner of the New York Times Sidney Award, and a two-time finalist for the Gerald Loeb Award for Distinguished Business and Financial Journalism.',
        reviews:'No review Found',
        tags:['Girls PGs','Only Two Sharing'],
      },
      {
        name:'RR Girls PG',
        id:'103',
        Owner:['M.Samuel', '8769808798'],
        Address:'#20, 20th B Cross, near Rama Temple , Sri Ram temple road, Ejipura, Bangalore',
        price:6999,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/front page/bpg3.webp',
        aboutTheBook:'"Atomic Habits" by James Clear is a bestselling self-help book that focuses on the power of small habits and their impact on our lives. It provides a framework for understanding habit formation and offers practical strategies to create positive habits and break negative ones. Clear explores the habit loop, discusses the importance of cues and rewards, and suggests techniques to make habits obvious, attractive, easy, and satisfying. The book also addresses challenges like procrastination and offers advice on staying motivated and overcoming setbacks. "Atomic Habits" is known for its practicality and evidence-based approach, and it has become a popular resource for personal growth and behavior change',
        aboutTheOwner:'James Clear is an expert on habits and decision making. He made his name as the Owner of one of the fastest-growing email newsletters in history, which grew from zero to 100,000 subscribers in under two years. Today, his newsletter has over 400,000 subscribers and his articles at jamesclear receive 10 million hits each year. His work frequently appears in publications including the New York Times, Forbes and Business Insider',
        reviews:'No review Found',
        tags:['Girls PGs','Only Two Sharing'],
      },
      {
        name:'Sri Durga Unisex PG ',
        id:'104',
        Owner:['Ramudu', '9878990897'],
        Address:'Arul Arcade, Babusapalya Main Rd, Chikka Nanjunda Reddy Layout, , Bank Avenue Colony, Horamavu, Bengaluru, Karnataka 560043',
        price:7999,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/front page/bpg4.webp',
        aboutTheBook:'"Atomic Habits" by James Clear is a bestselling self-help book that focuses on the power of small habits and their impact on our lives. It provides a framework for understanding habit formation and offers practical strategies to create positive habits and break negative ones. Clear explores the habit loop, discusses the importance of cues and rewards, and suggests techniques to make habits obvious, attractive, easy, and satisfying. The book also addresses challenges like procrastination and offers advice on staying motivated and overcoming setbacks. "Atomic Habits" is known for its practicality and evidence-based approach, and it has become a popular resource for personal growth and behavior change',
        aboutTheOwner:'James Clear is an expert on habits and decision making. He made his name as the Owner of one of the fastest-growing email newsletters in history, which grew from zero to 100,000 subscribers in under two years. Today, his newsletter has over 400,000 subscribers and his articles at jamesclear receive 10 million hits each year. His work frequently appears in publications including the New York Times, Forbes and Business Insider',
        reviews:'No review Found',
        tags:['Unisex PGs','Two Sharing'],
      },
      {
        name:'Hema Deluxe Girls PG',
        id:'105',
        Owner:['Hemavathi', '9887790808'],
        Address:'53/17, Abbiah Reddy Street, near Celebrity Arch , Dodda tuguru, E city 1 , Bangalore 100',
        price:9999,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/front page/bpg5.webp',
        aboutTheBook:'"Atomic Habits" by James Clear is a bestselling self-help book that focuses on the power of small habits and their impact on our lives. It provides a framework for understanding habit formation and offers practical strategies to create positive habits and break negative ones. Clear explores the habit loop, discusses the importance of cues and rewards, and suggests techniques to make habits obvious, attractive, easy, and satisfying. The book also addresses challenges like procrastination and offers advice on staying motivated and overcoming setbacks. "Atomic Habits" is known for its practicality and evidence-based approach, and it has become a popular resource for personal growth and behavior change',
        aboutTheOwner:'James Clear is an expert on habits and decision making. He made his name as the Owner of one of the fastest-growing email newsletters in history, which grew from zero to 100,000 subscribers in under two years. Today, his newsletter has over 400,000 subscribers and his articles at jamesclear receive 10 million hits each year. His work frequently appears in publications including the New York Times, Forbes and Business Insider',
        reviews:'No review Found',
        tags:['Premium PGs','Three Sharing'],
      },
      {
        name:'Ganesh Boys PG',
        id:'106',
        Owner:['Ganesh Reddy', '9879987878'],
        Address:'#8, 1St cross, Kaveri Layout, , Tavarekere Main Road, Bangalore 560029',
        price:7499,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/front page/bpg6.webp',
        aboutTheBook:'"Atomic Habits" by James Clear is a bestselling self-help book that focuses on the power of small habits and their impact on our lives. It provides a framework for understanding habit formation and offers practical strategies to create positive habits and break negative ones. Clear explores the habit loop, discusses the importance of cues and rewards, and suggests techniques to make habits obvious, attractive, easy, and satisfying. The book also addresses challenges like procrastination and offers advice on staying motivated and overcoming setbacks. "Atomic Habits" is known for its practicality and evidence-based approach, and it has become a popular resource for personal growth and behavior change',
        aboutTheOwner:'James Clear is an expert on habits and decision making. He made his name as the Owner of one of the fastest-growing email newsletters in history, which grew from zero to 100,000 subscribers in under two years. Today, his newsletter has over 400,000 subscribers and his articles at jamesclear receive 10 million hits each year. His work frequently appears in publications including the New York Times, Forbes and Business Insider',
        reviews:'No review Found',
        tags:['Boys PGs','Three Sharing'],
      },
      {
        name:'Vinay Premium Unisex PG ',
        id:'107',
        Owner:['K.Vinay Kumar', '9878767090'],
        Address:'Jaico Publishing House',
        price:9499,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/front page/bpg7.webp',
        aboutTheBook:'"Atomic Habits" by James Clear is a bestselling self-help book that focuses on the power of small habits and their impact on our lives. It provides a framework for understanding habit formation and offers practical strategies to create positive habits and break negative ones. Clear explores the habit loop, discusses the importance of cues and rewards, and suggests techniques to make habits obvious, attractive, easy, and satisfying. The book also addresses challenges like procrastination and offers advice on staying motivated and overcoming setbacks. "Atomic Habits" is known for its practicality and evidence-based approach, and it has become a popular resource for personal growth and behavior change',
        aboutTheOwner:'James Clear is an expert on habits and decision making. He made his name as the Owner of one of the fastest-growing email newsletters in history, which grew from zero to 100,000 subscribers in under two years. Today, his newsletter has over 400,000 subscribers and his articles at jamesclear receive 10 million hits each year. His work frequently appears in publications including the New York Times, Forbes and Business Insider',
        reviews:'No review Found',
        tags:['Premium PGs','Two Sharing'],
      },
      {
        name:'The Eagle Girls PG ',
        id:'108',
        Owner:['Mahalakshmi Sri', '9076654655'],
        Address:'Site No. 3, 1st Cross Road, Lorry Stand, , Godown Street, Yeshwanthpur, Bangalore 560022',
        price:6499,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/front page/bpg8.webp',
        aboutTheBook:'"Atomic Habits" by James Clear is a bestselling self-help book that focuses on the power of small habits and their impact on our lives. It provides a framework for understanding habit formation and offers practical strategies to create positive habits and break negative ones. Clear explores the habit loop, discusses the importance of cues and rewards, and suggests techniques to make habits obvious, attractive, easy, and satisfying. The book also addresses challenges like procrastination and offers advice on staying motivated and overcoming setbacks. "Atomic Habits" is known for its practicality and evidence-based approach, and it has become a popular resource for personal growth and behavior change',
        aboutTheOwner:'James Clear is an expert on habits and decision making. He made his name as the Owner of one of the fastest-growing email newsletters in history, which grew from zero to 100,000 subscribers in under two years. Today, his newsletter has over 400,000 subscribers and his articles at jamesclear receive 10 million hits each year. His work frequently appears in publications including the New York Times, Forbes and Business Insider',
        reviews:'No review Found',
        tags:['Girls PGs','Three Sharing'],
      },

      // Fiction Books
     //--------------------------- Romance Book ------------------------------------------ 
       {
        name:'Golden Villa Girls PG',
        id:'201',
        Owner:['Gayathri Devi', '9086776835'],
        Address:'Site No-99 formed in Sy.No.47, Old Khatha No-444, New Khatha No- in F.No-9-928 and in F-11-1137, , Electronic City Housing Layout, Konappana Agrahara Village, Begur Hobli, Bangalore South Taluk',
        price:7999,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/Romance/p1.webp',
        aboutTheBook:'"Romeo and Juliet" is a tragic love story written by William Shakespeare. It revolves around two young lovers, Romeo and Juliet, who come from feuding families. They fall deeply in love but face numerous obstacles due to their families ongoing conflict. In a desperate attempt to be together, they secretly marry with the help of Friar Laurence. However, a series of misunderstandings and tragic events unfold, leading to their untimely deaths. The play explores themes of love, fate, and the destructive power of hate. It is a timeless tale of passion, sacrifice, and the consequences of impulsive actions.',
        aboutTheOwner:'William Shakespeare was an English playwright, poet, and actor who lived from 1564 to 1616. He is widely regarded as one of the greatest writers in the English language. Shakespeare wrote numerous plays and sonnets that explore themes of love, power, and human nature. His works, including "Romeo and Juliet," "Hamlet," and "Macbeth," continue to be celebrated for their profound insights and enduring impact on literature and theater. Shakespeare language and storytelling abilities have made him an iconic figure in the world of literature',
        reviews:'No review Found',
        tags:['Girls PGs','Three Sharing'],
      },
      {
        name:'Sree Guru Gents PG',
        id:'202',
        Owner:['Ravinder Singh', '8956754465'],
        Address:'Site No 15 No 13/2 Shambhoganahalli Village , Hesaraghatta Hobli, Bangalore 560089',
        price:7499,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/Romance/p2.webp',
        aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
        aboutTheOwner:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The Owner interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
        reviews:'No review Found',
        tags:['Boys PGs','three Sharing'],
      },
      {
      name:'RRR Unisex PG',
        id:'203',
        Owner:['Savi Sharma', '9954278535'],
        Address:'1st Cross Rd, 19, Sarjapur Junction 2nd Cross Rd, Ibbaluru , Bellandur, Bengaluru, Karnataka 560103',
        price:9999,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/Romance/p3.webp',
        aboutTheBook:'Meera, a fledgling writer who is in search of a story that can touch millions of lives.Vivaan, assistant branch manager at Citibank, who dreams of travelling the world.Kabir, a café manager who desires something of his own. Nisha, the despondent café customer who keeps secrets of her own.Everyone has their own story, but what happens when these four lives are woven together?Pull up a chair in Kafe Kabir and watch them explore friendship and love, writing their own pages of life from the cosy café to the ends of the world.',
        aboutTheOwner:'A simple girl from Surat, Savi Sharma is the co-founder of the motivational media blog Life and People. Everyone Has a Story is her debut novel inspired by stories around her. ',
        reviews:'No review Found',
        tags:['Unisex PGs','Three Sharing'],
      },

      {
        name:'Thulasi Ladies PG',
          id:'204',
          Owner:['Thulasi', '8798648948'],
          Address:'Arul Arcade, Babusapalya Main Rd, Chikka Nanjunda Reddy Layout , Bank Avenue Colony, Horamavu, Bengaluru, Karnataka 560043',
          price:7499,
          availability:'Availabilty',
          shippingtime:'Usually ships 1-3 Days',
          favorite:false,
          star :5.0,
          imageUrl:'/assets/Romance/p4.webp',
          aboutTheBook:'Love is that which inspires us. Love is that which makes us believe in miracles. Love is that changes one to be a good human being. Karan and Vandana, two teenagers were mad and made for each other. How does love inspire them? How does love make them believe in destiny? How does love change their world... Find in I will never find another U',
          aboutTheOwner:'Kumar Kaustubh is an engineering student, lives in Jamshedpur. He has written 4 novels and scripts for many short films. He aspires to be an adventure traveller.',
          reviews:'No review Found',
          tags:['Girls PGs','Three Sharing'],
        },

        {
          name:'Rahul Girls PG',
            id:'205',
            Owner:['Rahul Reddy', '9947624990'],
            Address:'1st Cross Rd, 19, Sarjapur Junction 2nd Cross Rd, Ibbaluru , Bellandur, Bengaluru, Karnataka 560103',
            price:9999,
            availability:'Availabilty',
            shippingtime:'Usually ships 1-3 Days',
            favorite:false,
            star :5.0,
            imageUrl:'/assets/Romance/p5.webp',
            aboutTheBook:'With You... Without You... is set in the 90’s Calcutta, with its main protagonist Jags, Ishika and Karan dealing with a plethora of school-life problems starting from board exams to relationship issues. It is a coming of age tale on how the inseparable trio gets lost in the melee of the world soon after school life ends, only to be united decades later. Everyone who loves their school life would be able to relate to this story written in a very lucid manner.',
            aboutTheOwner:'Born in the Calcutta of 80s, he has spent a little over a decade sailing around the globe. This book was conceived during one such voyage where he had set out to conquer a new land. Apart from writing, he has a keen interest in touching peoples life and bring a smile on their faces.',
            reviews:'No review Found',
            tags:['Girls PGs','Three Sahring'],
          },

          {
            name:'Surys Mens PG',
              id:'206',
              Owner:['Suryakumar', '9966858433'],
              Address:'Site No -82, 5th Cross, Nanjareddy Colony , Murgeshpalya, Varthur, Bangalore -560017',
              price:8499,
              availability:'Availabilty',
              shippingtime:'Usually ships 1-3 Days',
              favorite:false,
              star :5.0,
              imageUrl:'/assets/Romance/p6.webp',
              aboutTheBook:'',
              aboutTheOwner:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The Owner interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
              reviews:'No review Found',
              tags:['Boys PGs','Three Sharing'],
            },

            {
              name:'Blue Sky PG For Gents',
                id:'207',
                Owner:['Pavan Reddy', '8978580896'],
                Address:'Abbaiah Reddy Street , Doddathoguru, Electronic City Phase-1',
                price:7499,
                availability:'Availabilty',
                shippingtime:'Usually ships 1-3 Days',
                favorite:false,
                star :5.0,
                imageUrl:'/assets/Romance/p7.webp',
                aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
                aboutTheOwner:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The Owner interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
                reviews:'No review Found',
                tags:['Boys PGs','Three Sharing'],
              },

              {
                name:'Five Star Girls PG',
                  id:'208',
                  Owner:['Savi Sharma','9954864389'],
                  Address:'near Oracle, Magna Infotech and other IT companies, 3rd Cross Rd, Venkateshwara Layout, , S.G. Palya, Bengaluru, Karnataka 560029',
                  price:7999,
                  availability:'Availabilty',
                  shippingtime:'Usually ships 1-3 Days',
                  favorite:false,
                  star :5.0,
                  imageUrl:'/assets/Romance/p8.webp',
                  aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
                  aboutTheOwner:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The Owner interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
                  reviews:'No review Found',
                  tags:['Girls PGs','Three Sharing'],
                },

                {
                  name:'RRJS Gents PG',
                    id:'209',
                    Owner:['K V MohanKumar', '9785645430'],
                    Address:'NO.35, KHATA NO.89, HOUSE LIST NO.35/2 , NAGAWARA VILLAGE, KASABA HOBLI, Nagawara, Bengaluru, Karnataka',
                    price:6499,
                    availability:'Availabilty',
                    shippingtime:'Usually ships 1-3 Days',
                    favorite:false,
                    star :5.0,
                    imageUrl:'/assets/Romance/p9.webp',
                    aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
                    aboutTheOwner:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The Owner interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
                    reviews:'No review Found',
                    tags:['Boys PGs','Two Sharing' ],
                  },

                  {
                    name:'Ananya Ladies PG',
                      id:'210',
                      Owner:['S.K.Sood', '9947754324'],
                      Address:'Site No. 258/3,Khatha No.115/258/2,3,4,6 , Bommanahali Village,Begur Hobli, Bengaluru South Taluk',
                      price:7499,
                      availability:'Availabilty',
                      shippingtime:'Usually ships 1-3 Days',
                      favorite:false,
                      star :5.0,
                      imageUrl:'/assets/Romance/p10.webp',
                      aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
                      aboutTheOwner:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The Owner interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
                      reviews:'No review Found',
                      tags:['Girls PGs','Three Sharing'],
                    },

                    //----------------Adventure Books------------------------

                    {
                      name:'Swarna PG For Ladies',
                      id:'301',
                      Owner:['Swarnalata', '9958563770'],
                      Address:'KIADB Layout, Beside SBI Atm, 1st Main Rd , Konappana Agrahara, Electronic City',
                      price:7999,
                      availability:'Availabilty',
                      shippingtime:'Usually ships 1-3 Days',
                      favorite:false,
                      star :5.0,
                      imageUrl:'/assets/Romance/p11.webp',
                      aboutTheBook:'"Romeo and Juliet" is a tragic love story written by William Shakespeare. It revolves around two young lovers, Romeo and Juliet, who come from feuding families. They fall deeply in love but face numerous obstacles due to their families ongoing conflict. In a desperate attempt to be together, they secretly marry with the help of Friar Laurence. However, a series of misunderstandings and tragic events unfold, leading to their untimely deaths. The play explores themes of love, fate, and the destructive power of hate. It is a timeless tale of passion, sacrifice, and the consequences of impulsive actions.',
                      aboutTheOwner:'William Shakespeare was an English playwright, poet, and actor who lived from 1564 to 1616. He is widely regarded as one of the greatest writers in the English language. Shakespeare wrote numerous plays and sonnets that explore themes of love, power, and human nature. His works, including "Romeo and Juliet," "Hamlet," and "Macbeth," continue to be celebrated for their profound insights and enduring impact on literature and theater. Shakespeare language and storytelling abilities have made him an iconic figure in the world of literature',
                      reviews:'No review Found',
                      tags:['Girls PGs','Three Sharing',],
                    },
                    {
                      name:'Krishna Mens PG',
                      id:'302',
                      Owner:['Krishna Nayak', '9958600740'],
                      Address:'Building 15, Sy no 35/2,Konappana Agrahara village Near Hosur Road, , Electronic City Phase II, Bengaluru, Karnataka 560100',
                      price:7499,
                      availability:'Availabilty',
                      shippingtime:'Usually ships 1-3 Days',
                      favorite:false,
                      star :5.0,
                      imageUrl:'/assets/Romance/pp1.jpg',
                      aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
                      aboutTheOwner:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The Owner interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
                      reviews:'No review Found',
                      tags:['Boys PGs','Three Sharing'],
                    },
                    {
                    name:'Rohit Unisex PG ',
                      id:'203',
                      Owner:['Rohit Reddy', '9958321603'],
                      Address:'2nd Main Rd, Whitefield, Bengaluru, Karnataka ',
                      price:9999,
                      availability:'Availabilty',
                      shippingtime:'Usually ships 1-3 Days',
                      favorite:false,
                      star :5.0,
                      imageUrl:'/assets/Romance/pp2.webp',
                      aboutTheBook:'Meera, a fledgling writer who is in search of a story that can touch millions of lives.Vivaan, assistant branch manager at Citibank, who dreams of travelling the world.Kabir, a café manager who desires something of his own. Nisha, the despondent café customer who keeps secrets of her own.Everyone has their own story, but what happens when these four lives are woven together?Pull up a chair in Kafe Kabir and watch them explore friendship and love, writing their own pages of life from the cosy café to the ends of the world.',
                      aboutTheOwner:'A simple girl from Surat, Savi Sharma is the co-founder of the motivational media blog Life and People. Everyone Has a Story is her debut novel inspired by stories around her. ',
                      reviews:'No review Found',
                      tags:['Unisex PGs','Two Sharing']
                    },
              
                    {
                      name:'Jayalakshmi Unisex PG',
                        id:'204',
                        Owner:['Jayalakshmi', '9086486347'],
                        Address:'09, Munivenkatappa Layout, 4th Cross, Next to Nagawara Bridge, Nagawara Main Road, Vyalikaval HBCS Layout, , Nagavara, Bengaluru, Karnataka 560045',
                        price:7999,
                        availability:'Availabilty',
                        shippingtime:'Usually ships 1-3 Days',
                        favorite:false,
                        star :5.0,
                        imageUrl:'/assets/Romance/pp3.webp',
                        aboutTheBook:'Love is that which inspires us. Love is that which makes us believe in miracles. Love is that changes one to be a good human being. Karan and Vandana, two teenagers were mad and made for each other. How does love inspire them? How does love make them believe in destiny? How does love change their world... Find in I will never find another U',
                        aboutTheOwner:'Kumar Kaustubh is an engineering student, lives in Jamshedpur. He has written 4 novels and scripts for many short films. He aspires to be an adventure traveller.',
                        reviews:'No review Found',
                        tags:['Unisex PGs','Two Sharing']
                      },
              
                      {
                        name:'Meenakshi Ladies PG',
                          id:'205',
                          Owner:['Kushal Mitra', '8065843866'],
                          Address:'29, Sarjapur Main Rd, Junnasandra Road, Junnasandra, Rainbow Drive , Halanayakanahalli, Bengaluru, Karnataka',
                          price:7999,
                          availability:'Availabilty',
                          shippingtime:'Usually ships 1-3 Days',
                          favorite:false,
                          star :5.0,
                          imageUrl:'/assets/Romance/pp5.webp',
                          aboutTheBook:'With You... Without You... is set in the 90’s Calcutta, with its main protagonist Jags, Ishika and Karan dealing with a plethora of school-life problems starting from board exams to relationship issues. It is a coming of age tale on how the inseparable trio gets lost in the melee of the world soon after school life ends, only to be united decades later. Everyone who loves their school life would be able to relate to this story written in a very lucid manner.',
                          aboutTheOwner:'Born in the Calcutta of 80s, he has spent a little over a decade sailing around the globe. This book was conceived during one such voyage where he had set out to conquer a new land. Apart from writing, he has a keen interest in touching peoples life and bring a smile on their faces.',
                          reviews:'No review Found',
                          tags:['Girls PGs','Three Sharing']
                        },
              
                       

//-------------------------Mystery Book --------------------------------------
{
  name:'Hi Fi Unisex PG',
  id:'201',
  Owner:['Ruskin Bond', '8097648650'],
  Address:'Site No.11, Khatha No.63-81-11 In 11th 1st Cross Rd, , Venkateshwara Layout, Bengaluru, Karnataka 560029',
  price:8499,
  availability:'Availabilty',
  shippingtime:'Usually ships 1-3 Days',
  favorite:false,
  star :5.0,
  imageUrl:'/assets/Romance/pp6.webp',
  aboutTheBook:'"Romeo and Juliet" is a tragic love story written by William Shakespeare. It revolves around two young lovers, Romeo and Juliet, who come from feuding families. They fall deeply in love but face numerous obstacles due to their families ongoing conflict. In a desperate attempt to be together, they secretly marry with the help of Friar Laurence. However, a series of misunderstandings and tragic events unfold, leading to their untimely deaths. The play explores themes of love, fate, and the destructive power of hate. It is a timeless tale of passion, sacrifice, and the consequences of impulsive actions.',
  aboutTheOwner:'William Shakespeare was an English playwright, poet, and actor who lived from 1564 to 1616. He is widely regarded as one of the greatest writers in the English language. Shakespeare wrote numerous plays and sonnets that explore themes of love, power, and human nature. His works, including "Romeo and Juliet," "Hamlet," and "Macbeth," continue to be celebrated for their profound insights and enduring impact on literature and theater. Shakespeare language and storytelling abilities have made him an iconic figure in the world of literature',
  reviews:'No review Found',
  tags:['Unisex PGs','Two Sharing'],
},
{
  name:'KKR PG for Girls',
  id:'202',
  Owner:['Shankar Nayak', '9087976544'],
  Address:'M& N Pg ,7th cross street, Back Side, , Anand Nagar, Aswath Nagar, kalamandhir, Bengaluru, Karnataka',
  price:8499,
  availability:'Availabilty',
  shippingtime:'Usually ships 1-3 Days',
  favorite:false,
  star :5.0,
  imageUrl:'/assets/Romance/pp7.webp',
  aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
  aboutTheOwner:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The Owner interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
  reviews:'No review Found',
  tags:['Girls PGs','Three Sharing']
},
{
name:'Namma Boys PG ',
  id:'203',
  Owner:['Harshvardhan Rao', '8098975685'],
  Address:'Spice Garden Layout, Lakshminarayana Pura , AECS Layout, Marathahalli',
  price:6999,
  availability:'Availabilty',
  shippingtime:'Usually ships 1-3 Days',
  favorite:false,
  star :5.0,
  imageUrl:'/assets/Romance/pp8.webp',
  aboutTheBook:'Meera, a fledgling writer who is in search of a story that can touch millions of lives.Vivaan, assistant branch manager at Citibank, who dreams of travelling the world.Kabir, a café manager who desires something of his own. Nisha, the despondent café customer who keeps secrets of her own.Everyone has their own story, but what happens when these four lives are woven together?Pull up a chair in Kafe Kabir and watch them explore friendship and love, writing their own pages of life from the cosy café to the ends of the world.',
  aboutTheOwner:'A simple girl from Surat, Savi Sharma is the co-founder of the motivational media blog Life and People. Everyone Has a Story is her debut novel inspired by stories around her. ',
  reviews:'No review Found',
  tags:['Boys PGs','Three Sharing'],
},

{
  name:'Namma Ladies PG',
    id:'204',
    Owner:['Girish ', '7098675970'],
    Address:'Arul Arcade, Babusapalya Main Rd, Chikka Nanjunda Reddy Layout, , Bank Avenue Colony, Horamavu, Bengaluru, Karnataka 560043',
    price:7999,
    availability:'Availabilty',
    shippingtime:'Usually ships 1-3 Days',
    favorite:false,
    star :5.0,
    imageUrl:'/assets/Romance/pp9.webp',
    aboutTheBook:'Love is that which inspires us. Love is that which makes us believe in miracles. Love is that changes one to be a good human being. Karan and Vandana, two teenagers were mad and made for each other. How does love inspire them? How does love make them believe in destiny? How does love change their world... Find in I will never find another U',
    aboutTheOwner:'Kumar Kaustubh is an engineering student, lives in Jamshedpur. He has written 4 novels and scripts for many short films. He aspires to be an adventure traveller.',
    reviews:'No review Found',
    tags:['Girls PGs','Three Sharing']
  },

  {
    name:'Shivani Ladies PG',
      id:'205',
      Owner:['Shivani Gupta', '9048532851'],
      Address:'#8, 1St cross, Kaveri Layout, , Tavarekere Main Road, Bangalore 560029',
      price:8999,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'/assets/Romance/pp10.webp',
      aboutTheBook:'With You... Without You... is set in the 90’s Calcutta, with its main protagonist Jags, Ishika and Karan dealing with a plethora of school-life problems starting from board exams to relationship issues. It is a coming of age tale on how the inseparable trio gets lost in the melee of the world soon after school life ends, only to be united decades later. Everyone who loves their school life would be able to relate to this story written in a very lucid manner.',
      aboutTheOwner:'Born in the Calcutta of 80s, he has spent a little over a decade sailing around the globe. This book was conceived during one such voyage where he had set out to conquer a new land. Apart from writing, he has a keen interest in touching peoples life and bring a smile on their faces.',
      reviews:'No review Found',
      tags:['Girls PGs','Three Sharing'],
    },

    
    //------------------------Fantasy Book -----------------------------
    {
      name:'OM Unisex PG',
      id:'201',
      Owner:['Omkar Reddy', '7099847658'],
      Address:'Arul Arcade, Babusapalya Main Rd, Chikka Nanjunda Reddy Layout , Bank Avenue Colony, Horamavu, Bengaluru, Karnataka 560043',
      price:9499,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'/assets/Romance/pp11.webp',
      aboutTheBook:'"Romeo and Juliet" is a tragic love story written by William Shakespeare. It revolves around two young lovers, Romeo and Juliet, who come from feuding families. They fall deeply in love but face numerous obstacles due to their families ongoing conflict. In a desperate attempt to be together, they secretly marry with the help of Friar Laurence. However, a series of misunderstandings and tragic events unfold, leading to their untimely deaths. The play explores themes of love, fate, and the destructive power of hate. It is a timeless tale of passion, sacrifice, and the consequences of impulsive actions.',
      aboutTheOwner:'William Shakespeare was an English playwright, poet, and actor who lived from 1564 to 1616. He is widely regarded as one of the greatest writers in the English language. Shakespeare wrote numerous plays and sonnets that explore themes of love, power, and human nature. His works, including "Romeo and Juliet," "Hamlet," and "Macbeth," continue to be celebrated for their profound insights and enduring impact on literature and theater. Shakespeare language and storytelling abilities have made him an iconic figure in the world of literature',
      reviews:'No review Found',
      tags:['Unisex PGs','Two Sharing'],
    },
    {
      name:'Surya Unisex PG',
      id:'202',
      Owner:['Surya', '7099889023'],
      Address:'near Oracle, Magna Infotech and other IT companies, 3rd Cross Rd, Venkateshwara Layout, , S.G. Palya, Bengaluru, Karnataka 560029',
      price:8999,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'/assets/Romance/pp12.webp',
      aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
      aboutTheOwner:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The Owner interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
      reviews:'No review Found',
      tags:['Unisex PGs',' Two Sharing'],
    },
    {
    name:'MMS Ladies PG',
      id:'203',
      Owner:['M.Mani Shankar', '8876905317'],
      Address:'Site No. 258/3,Khatha No.115/258/2,3,4,6 , Bommanahali Village,Begur Hobli, Bengaluru South Taluk',
      price:8499,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'/assets/Romance/pp13.webp',
      aboutTheBook:'Meera, a fledgling writer who is in search of a story that can touch millions of lives.Vivaan, assistant branch manager at Citibank, who dreams of travelling the world.Kabir, a café manager who desires something of his own. Nisha, the despondent café customer who keeps secrets of her own.Everyone has their own story, but what happens when these four lives are woven together?Pull up a chair in Kafe Kabir and watch them explore friendship and love, writing their own pages of life from the cosy café to the ends of the world.',
      aboutTheOwner:'A simple girl from Surat, Savi Sharma is the co-founder of the motivational media blog Life and People. Everyone Has a Story is her debut novel inspired by stories around her. ',
      reviews:'No review Found',
      tags:['Girls PGs','Three Sharing'],
    },

    {
      name:'Yaswanth Gents PG',
        id:'204',
        Owner:['Yaswanth', '8899608527'],
        Address:'Building 15, Sy no 35/2,Konappana Agrahara village Near Hosur Road, , Electronic City Phase II, Bengaluru, Karnataka 560100',
        price:8499,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/Romance/pp14.webp',
        aboutTheBook:'Love is that which inspires us. Love is that which makes us believe in miracles. Love is that changes one to be a good human being. Karan and Vandana, two teenagers were mad and made for each other. How does love inspire them? How does love make them believe in destiny? How does love change their world... Find in I will never find another U',
        aboutTheOwner:'Kumar Kaustubh is an engineering student, lives in Jamshedpur. He has written 4 novels and scripts for many short films. He aspires to be an adventure traveller.',
        reviews:'No review Found',
        tags:['Boys PGs','Three Sharing'],
      },

      {
        name:'Vishwash Unisex PG',
          id:'205',
          Owner:['Vishwash', '9988463157'],
          Address:'09, Munivenkatappa Layout, 4th Cross, Next to Nagawara Bridge, Nagawara Main Road, Vyalikaval HBCS Layout, , Nagavara, Bengaluru, Karnataka 560045',
          price:8999,
          availability:'Availabilty',
          shippingtime:'Usually ships 1-3 Days',
          favorite:false,
          star :5.0,
          imageUrl:'/assets/Romance/pp15.webp',
          aboutTheBook:'With You... Without You... is set in the 90’s Calcutta, with its main protagonist Jags, Ishika and Karan dealing with a plethora of school-life problems starting from board exams to relationship issues. It is a coming of age tale on how the inseparable trio gets lost in the melee of the world soon after school life ends, only to be united decades later. Everyone who loves their school life would be able to relate to this story written in a very lucid manner.',
          aboutTheOwner:'Born in the Calcutta of 80s, he has spent a little over a decade sailing around the globe. This book was conceived during one such voyage where he had set out to conquer a new land. Apart from writing, he has a keen interest in touching peoples life and bring a smile on their faces.',
          reviews:'No review Found',
          tags:['Unisex PGs','Two Sharing'],
        },

        
    //---------------------------Children Book---------------------------
    {
      name:'Adhi Ladies PG',
      id:'201',
      Owner:['Adhi', '8890654381'],
      Address:'No. 9, Assessment No. 147/2 , Nagawara Village, , Nagavara Village, Kasaba Hobli, Bengaluru - 560045',
      price:9999,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'/assets/Romance/pp16.webp',
      aboutTheBook:'"Romeo and Juliet" is a tragic love story written by William Shakespeare. It revolves around two young lovers, Romeo and Juliet, who come from feuding families. They fall deeply in love but face numerous obstacles due to their families ongoing conflict. In a desperate attempt to be together, they secretly marry with the help of Friar Laurence. However, a series of misunderstandings and tragic events unfold, leading to their untimely deaths. The play explores themes of love, fate, and the destructive power of hate. It is a timeless tale of passion, sacrifice, and the consequences of impulsive actions.',
      aboutTheOwner:'William Shakespeare was an English playwright, poet, and actor who lived from 1564 to 1616. He is widely regarded as one of the greatest writers in the English language. Shakespeare wrote numerous plays and sonnets that explore themes of love, power, and human nature. His works, including "Romeo and Juliet," "Hamlet," and "Macbeth," continue to be celebrated for their profound insights and enduring impact on literature and theater. Shakespeare language and storytelling abilities have made him an iconic figure in the world of literature',
      reviews:'No review Found',
      tags:['Girls PGs','Three Sharing'],
    },
    {
      name:'SSS Gents PG',
      id:'202',
      Owner:['Navneet', '7790753721'],
      Address:'No. 99/A Assessment No. 75 , situated at Nagawara Village, Bangalore',
      price:8499,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'/assets/Romance/pp17.webp',
      aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
      aboutTheOwner:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The Owner interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
      reviews:'No review Found',
      tags:['Boys PGs','Three Sharing'],
    },
    {
    name:'Star Live Ladies PG',
      id:'203',
      Owner:['Navneet', '9955997732'],
      Address:'No. 99/A Assessment No. 75 , situated at Nagawara Village, Bangalore',
      price:7999,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'/assets/Romance/pp18.webp',
      aboutTheBook:'Meera, a fledgling writer who is in search of a story that can touch millions of lives.Vivaan, assistant branch manager at Citibank, who dreams of travelling the world.Kabir, a café manager who desires something of his own. Nisha, the despondent café customer who keeps secrets of her own.Everyone has their own story, but what happens when these four lives are woven together?Pull up a chair in Kafe Kabir and watch them explore friendship and love, writing their own pages of life from the cosy café to the ends of the world.',
      aboutTheOwner:'A simple girl from Surat, Savi Sharma is the co-founder of the motivational media blog Life and People. Everyone Has a Story is her debut novel inspired by stories around her. ',
      reviews:'No review Found',
      tags:['Girls PGs','Three Sharing'],
    },

    {
      name:'Grandma Unisex PG',
        id:'204',
        Owner:['Lalitha Iyer','7700859817'],
        Address:'1st Cross Rd, 19, Sarjapur Junction 2nd Cross Rd, Ibbaluru , Bellandur, Bengaluru, Karnataka 560103',
        price:9999,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/Romance/pp19.webp',
        aboutTheBook:'Love is that which inspires us. Love is that which makes us believe in miracles. Love is that changes one to be a good human being. Karan and Vandana, two teenagers were mad and made for each other. How does love inspire them? How does love make them believe in destiny? How does love change their world... Find in I will never find another U',
        aboutTheOwner:'Kumar Kaustubh is an engineering student, lives in Jamshedpur. He has written 4 novels and scripts for many short films. He aspires to be an adventure traveller.',
        reviews:'No review Found',
        tags:['Unisex PGs','Two Sharing'],
      },

      {
        name:'Nirman Ladies PG',
          id:'205',
          Owner:['Nirman', '9966004488'],
          Address:'#59, 8th Cross Rd, Neeladri Nagar, , Electronics City Phase 1, Electronic City, Karnataka 560100',
          price:7499,
          availability:'Availabilty',
          shippingtime:'Usually ships 1-3 Days',
          favorite:false,
          star :5.0,
          imageUrl:'/assets/Romance/pp20.webp',
          aboutTheBook:'With You... Without You... is set in the 90’s Calcutta, with its main protagonist Jags, Ishika and Karan dealing with a plethora of school-life problems starting from board exams to relationship issues. It is a coming of age tale on how the inseparable trio gets lost in the melee of the world soon after school life ends, only to be united decades later. Everyone who loves their school life would be able to relate to this story written in a very lucid manner.',
          aboutTheOwner:'Born in the Calcutta of 80s, he has spent a little over a decade sailing around the globe. This book was conceived during one such voyage where he had set out to conquer a new land. Apart from writing, he has a keen interest in touching peoples life and bring a smile on their faces.',
          reviews:'No review Found',
          tags:['Girls PGs','Three Sharing'],
        },

        

    {
      name:'Hemanth PG For Gents',
      id:'201',
      Owner:['Hemanth', '9785654061'],
      Address:'13-25,9th cross road, , Rangadasappa Layout,Lakkasanda, Bangalore - 560030',
      price:6999,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'/assets/Romance/pp21.webp',
      aboutTheBook:'"Romeo and Juliet" is a tragic love story written by William Shakespeare. It revolves around two young lovers, Romeo and Juliet, who come from feuding families. They fall deeply in love but face numerous obstacles due to their families ongoing conflict. In a desperate attempt to be together, they secretly marry with the help of Friar Laurence. However, a series of misunderstandings and tragic events unfold, leading to their untimely deaths. The play explores themes of love, fate, and the destructive power of hate. It is a timeless tale of passion, sacrifice, and the consequences of impulsive actions.',
      aboutTheOwner:'William Shakespeare was an English playwright, poet, and actor who lived from 1564 to 1616. He is widely regarded as one of the greatest writers in the English language. Shakespeare wrote numerous plays and sonnets that explore themes of love, power, and human nature. His works, including "Romeo and Juliet," "Hamlet," and "Macbeth," continue to be celebrated for their profound insights and enduring impact on literature and theater. Shakespeare language and storytelling abilities have made him an iconic figure in the world of literature',
      reviews:'No review Found',
      tags:['Boys PGs','Four Sharing'],
    },
    {
      name:'Shiridi Sai Unisex PG',
      id:'202',
      Owner:['Sudipto Das', '8890643216'],
      Address:'Building 1 35/2,Konappana Agrahara village Near Hosur, road, , Electronic City Phase II, Bengaluru, Karnataka',
      price:8999,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'/assets/Romance/pp22.webp',
      aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
      aboutTheOwner:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The Owner interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
      reviews:'No review Found',
      tags:['Unisex PGs','Three Sharing'],
    },
    {
    name:'VKB Premium Boys PG',
      id:'203',
      Owner:['Amish Tripathi', '7098643721'],
      Address:'101, 1st Main Rd, 8th cross, Maruti Nagar, , 1st Stage, BTM Layout, Bengaluru, Karnataka',
      price:8999,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'/assets/Romance/pp23.webp',
      aboutTheBook:'Meera, a fledgling writer who is in search of a story that can touch millions of lives.Vivaan, assistant branch manager at Citibank, who dreams of travelling the world.Kabir, a café manager who desires something of his own. Nisha, the despondent café customer who keeps secrets of her own.Everyone has their own story, but what happens when these four lives are woven together?Pull up a chair in Kafe Kabir and watch them explore friendship and love, writing their own pages of life from the cosy café to the ends of the world.',
      aboutTheOwner:'A simple girl from Surat, Savi Sharma is the co-founder of the motivational media blog Life and People. Everyone Has a Story is her debut novel inspired by stories around her. ',
      reviews:'No review Found',
      tags:['Premium PGs','Two Sharing'],
    },

    {
      name:'Hema Premium Girls PG',
        id:'204',
        Owner:['Hema', '8978569056'],
        Address:'2/2 , 80 feet road, DR Rajkumar Road, , Rajajinagar, Bengaluru',
        price:8999,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/Romance/pp24.webp',
        aboutTheBook:'Love is that which inspires us. Love is that which makes us believe in miracles. Love is that changes one to be a good human being. Karan and Vandana, two teenagers were mad and made for each other. How does love inspire them? How does love make them believe in destiny? How does love change their world... Find in I will never find another U',
        aboutTheOwner:'Kumar Kaustubh is an engineering student, lives in Jamshedpur. He has written 4 novels and scripts for many short films. He aspires to be an adventure traveller.',
        reviews:'No review Found',
        tags:['Girls PGs','Two Sharing'],
      },

      {
        name:'Raju  Premium Girls PG',
          id:'205',
          Owner:['Raju', '8967340954'],
          Address:'Plot No.12 (Plot No. 12/1), Old Khatha No. 1125/9, , Pattanduru Agrahara Village, K.R Puram Hobli, Bangalore',
          price:8999,
          availability:'Availabilty',
          shippingtime:'Usually ships 1-3 Days',
          favorite:false,
          star :5.0,
          imageUrl:'/assets/Romance/pp25.webp',
          aboutTheBook:'With You... Without You... is set in the 90’s Calcutta, with its main protagonist Jags, Ishika and Karan dealing with a plethora of school-life problems starting from board exams to relationship issues. It is a coming of age tale on how the inseparable trio gets lost in the melee of the world soon after school life ends, only to be united decades later. Everyone who loves their school life would be able to relate to this story written in a very lucid manner.',
          aboutTheOwner:'Born in the Calcutta of 80s, he has spent a little over a decade sailing around the globe. This book was conceived during one such voyage where he had set out to conquer a new land. Apart from writing, he has a keen interest in touching peoples life and bring a smile on their faces.',
          reviews:'No review Found',
          tags:['Premium PGs','Two Sharing'],
        },

        
    //-----------------------Biography -------------------------------

    {
      name:'Suchitra Premium Ladies PG',
      id:'201',
      Owner:['Suchitra', '8989886754'],
      Address:'SITE NO.2&3, ASSESSMENT NO.34/3,BBMP KHATA NO.789, , NAGWARA VILLAGE KASABA HOBLI,BANGALORE NORTH TALUK',
      price:7999,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'/assets/Romance/pp26.webp',
      aboutTheBook:'"Romeo and Juliet" is a tragic love story written by William Shakespeare. It revolves around two young lovers, Romeo and Juliet, who come from feuding families. They fall deeply in love but face numerous obstacles due to their families ongoing conflict. In a desperate attempt to be together, they secretly marry with the help of Friar Laurence. However, a series of misunderstandings and tragic events unfold, leading to their untimely deaths. The play explores themes of love, fate, and the destructive power of hate. It is a timeless tale of passion, sacrifice, and the consequences of impulsive actions.',
      aboutTheOwner:'William Shakespeare was an English playwright, poet, and actor who lived from 1564 to 1616. He is widely regarded as one of the greatest writers in the English language. Shakespeare wrote numerous plays and sonnets that explore themes of love, power, and human nature. His works, including "Romeo and Juliet," "Hamlet," and "Macbeth," continue to be celebrated for their profound insights and enduring impact on literature and theater. Shakespeare language and storytelling abilities have made him an iconic figure in the world of literature',
      reviews:'No review Found',
      tags:['Premium PGs','Three Sharing'],
    },
    {
      name:'SRSM Premium Ladies PG',
      id:'202',
      Owner:['SR.Sameer', '8967542390'],
      Address:'#12 Naveena Nilaya, , 5th Cross White Rose Layout Bangalore',
      price:8999,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'/assets/Romance/pp27.webp',
      aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
      aboutTheOwner:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The Owner interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
      reviews:'No review Found',
      tags:['Premium PGs','Two Sharing'],
    },
    {
    name:'Suraj Premium Boys PG',
      id:'203',
      Owner:['Suraj', '7890567834'],
      Address:'Kaveri Nagar, RK Hegde Nagar, Kothnur Narayanapura , Bengaluru, Karnataka 560077',
      price:7499,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'/assets/Romance/pp28.webp',
      aboutTheBook:'Meera, a fledgling writer who is in search of a story that can touch millions of lives.Vivaan, assistant branch manager at Citibank, who dreams of travelling the world.Kabir, a café manager who desires something of his own. Nisha, the despondent café customer who keeps secrets of her own.Everyone has their own story, but what happens when these four lives are woven together?Pull up a chair in Kafe Kabir and watch them explore friendship and love, writing their own pages of life from the cosy café to the ends of the world.',
      aboutTheOwner:'A simple girl from Surat, Savi Sharma is the co-founder of the motivational media blog Life and People. Everyone Has a Story is her debut novel inspired by stories around her. ',
      reviews:'No review Found',
      tags:['Premium PGs','Two Sharing'],
    },

    {
      name:'KSR Premium Unisex PG',
        id:'204',
        Owner:['KS.Reddy', '8956095432'],
        Address:'2nd Main Rd, Tavarekere, Maruti Nagar, , 1st Stage, BTM Layout, Bengaluru, Karnataka 560029',
        price:8999,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/Romance/pp29.webp',
        aboutTheBook:'Love is that which inspires us. Love is that which makes us believe in miracles. Love is that changes one to be a good human being. Karan and Vandana, two teenagers were mad and made for each other. How does love inspire them? How does love make them believe in destiny? How does love change their world... Find in I will never find another U',
        aboutTheOwner:'Kumar Kaustubh is an engineering student, lives in Jamshedpur. He has written 4 novels and scripts for many short films. He aspires to be an adventure traveller.',
        reviews:'No review Found',
        tags:['Premium PGs','Two Sharing'],
      },

      {
        name:'Royal Premium Unisex PG ',
          id:'205',
          Owner:['Mohanlal', '9067347821'],
          Address:'Coconut Garden Street , Old Madiwala, Madiwala, 1st Stage, BTM Layout, behind India Post - Madiwala Sub Post Office',
          price:9499,
          availability:'Availabilty',
          shippingtime:'Usually ships 1-3 Days',
          favorite:false,
          star :5.0,
          imageUrl:'/assets/Romance/pp30.webp',
          aboutTheBook:'With You... Without You... is set in the 90’s Calcutta, with its main protagonist Jags, Ishika and Karan dealing with a plethora of school-life problems starting from board exams to relationship issues. It is a coming of age tale on how the inseparable trio gets lost in the melee of the world soon after school life ends, only to be united decades later. Everyone who loves their school life would be able to relate to this story written in a very lucid manner.',
          aboutTheOwner:'Born in the Calcutta of 80s, he has spent a little over a decade sailing around the globe. This book was conceived during one such voyage where he had set out to conquer a new land. Apart from writing, he has a keen interest in touching peoples life and bring a smile on their faces.',
          reviews:'No review Found',
          tags:['Premium PGs','Two Sharing'],
        },

        
    //School Book

    {
      name:'Dhvani Premium Unisex PG',
        id:'1001',
        Owner:['S.K.Sood', ' 8956342176'],
        Address:'1470, 22nd Cross Road, 4th Main Rd, , Rajiv Gandhi Nagar, 7th Sector, HSR Layout, Bengaluru, Karnataka',
        price:9999,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/Romance/pp21.webp',
        aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
        aboutTheOwner:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The Owner interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
        reviews:'No review Found',
        tags:['Premium PGs','Two Sharing'],
      },
      {
        name:'MMS Premium Unisex PG',
          id:'1002',
          Owner:['MM.Shiva', '7890567890'],
          Address:'Ayra Business Center, #1 Mig, KHB colony, 5th Block, opp lakshmidevi park, Kormangala, , Bengaluru, Karnataka 560095',
          price:9999,
          availability:'Availabilty',
          shippingtime:'Usually ships 1-3 Days',
          favorite:false,
          star :5.0,
          imageUrl:'/assets/Romance/pp16.webp',
          aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
          aboutTheOwner:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The Owner interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
          reviews:'No review Found',
          tags:['Premium PGs','Two Sharing'],
        },
    ];
  }
}
